'use strict';

import ApiFooter from "./Api/Footer";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from '@fortawesome/free-solid-svg-icons'
import ApiVersion from "./Api/Version";
import Separator from "./Separator";
import ApiStatus from "./Api/Status";

export default function API(props) {
  const { name, version, source, lastDeploy, graphql, openapi, online } = props.data;
  const borderClass = online ? 'border-main-green' : 'border-error-red';
  return (
    <div className={'api-container ' + borderClass}>
      <div className="api-main">
        <div className="flex w-full">
          <img className="w-9 mr-5" src="api-icon.svg"></img>
          <div className="api-data">
            <div className="flex items-center justify-between">
              <div className="flex items-center justify-between gap-4">
                <span className="text-main-green font-semibold text-2xl">{name}</span>
                <span>
                  <a href="#" className="border p-2 rounded-full">
                    <FontAwesomeIcon color="white" icon={faLink}></FontAwesomeIcon>  
                  </a>
                </span>
                <ApiVersion version={version}></ApiVersion>
              </div>
              <div className="api-status">
                  <ApiStatus online={online}></ApiStatus>
                </div>
                
            </div>
            
            <div className="flex gap-2 items-center">
              <span>Generated by: { source }</span>
              <Separator />
              <span>Last deployed: { lastDeploy }</span>
            </div>
          </div>
          
        </div>
        
      </div>
      <hr className="text-dark-green my-2"/>
      <ApiFooter
        graphql={graphql}
        openapi={openapi}
      />
    </div>
  )
}