export const COLORS_ICON = ['main-green', 'white', 'main-dark-blue', 'error-red', 'warning-yellow']
export const COLORS_BUTTON = ['main-green', 'dark-green', 'light-green', 'main-dark-blue', 'dark-blue', 'light-blue', 'white', 'error-red', 'tertiary-blue', 'transparent']
export const COLORS_BORDERED_BOX = ['main-green', 'error-red', 'white', 'dark-blue', 'warning-yellow', 'transparent']
export const WHITE = 'white'
export const MAIN_DARK_BLUE = 'main-dark-blue'
export const MAIN_GREEN = 'main-green'
export const NONE = 'none'
export const SMALL = 'small'
export const MEDIUM = 'medium'
export const LARGE = 'large'
export const EXTRA_LARGE = 'extra-large'
export const SIZES = [SMALL, MEDIUM, LARGE, EXTRA_LARGE]
export const PADDING_SIZES = [NONE, ...SIZES]
export const BOX_SHADOW = 'box-shadow'
export const BACKGROUND_COLOR_OPAQUE = 'background-color-opaque'
export const UNDERLINE = 'underline'
export const HOVER_EFFECTS_BUTTONS = [BOX_SHADOW, BACKGROUND_COLOR_OPAQUE, UNDERLINE]
